version: 1.1.1
slug: ada
name: Hey Ada!
description: Voice assistant powered by Apex MCU.
url: https://github.com/apexinfosysindia/addons/ada
arch:
  - armhf
  - armv7
  - amd64
audio: true
homeassistant: 0.102.0
homeassistant_api: true
image: homeassistant/{arch}-addon-ada
init: false
options:
  stt: cloud
  tts: cloud
schema:
  stt: str
  tts: str
