---
build_from:
  aarch64: ghcr.io/apexinfosysindia/base-debian:trixie-2026.06.1
  amd64: ghcr.io/apexinfosysindia/base-debian:trixie-2026.06.1
args:
  LIBWEBSOCKET_VERSION: 4.5.8
  MOSQUITTO_VERSION: 2.1.2
  MOSQUITTO_AUTH_VERSION: 3.0.0
