---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armhf: ghcr.io/home-assistant/armhf-base-raspbian:bookworm
codenotary:
  signer: notary@apexinfosys.in
  base_image: notary@apexinfosys.in
args:
  DECONZ_VERSION: 2.28.1
